### ISSUE TITLE
filter checks by 'group' column in DB

### ISSUE THREAD

**Issue by orithk** [PLAY-behaviorome/workflow#36]
We added a column to the Databrary spread sheet that we will use to tag the sessions that pass and do not pass QA.

‘PLAY_Gold’ = Pass QA
‘PLAY_Silver’ = Fail QA
‘No_visit’ = visit was cancelled
'Pilot' = if pilot visit
If blank then QA is in progress

I would like that the reports to only include if the 'group' field is blank.
Also if there is any typo in 'PLAY_Gold’ ‘PLAY_Silver’ ‘No_visit’ 'Pilot'

Thank way the reports would only show the sessions that have not been through QA.

Thank you!

**Comment by rogilmore** [comment]
I used 'No_Visit' ('Visit' capitalized) for consistency with GEORG and the other group labels.

**Comment by rogilmore** [comment]
Fixed in 44c887907503d526540f857c79d00470c1a58dec
